---
# Credenciales para Grafana (encriptadas con Ansible Vault)
grafana_admin_password: "{{ vault_grafana_pass }}"

# Objetivos de Prometheus
prometheus_targets:
  masters:
    - "10.0.0.10:9100"  # node-exporter
    - "10.0.0.11:9100"
  workers:
    - "10.0.0.12:9100"
    - "10.0.0.13:9100"
