apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "microservice-a.fullname" . }}-pdb
  labels:
    {{- include "microservice-a.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "microservice-a.selectorLabels" . | nindent 6 }}
