- hosts: k8s_masters
  tasks:
    - name: Install k3s master
      shell: |
        curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" sh -
    - name: Get kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes
