- hosts: k8s
  become: true
  tasks:
    - name: Disable root SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: 'PermitRootLogin no'

    - name: Enable UFW
      ufw:
        state: enabled
